local ProfileTemplate = {
	Magnet = {
		Name = "BasicMagnet",
		Magnetism = 1,
	},

	OwnedMagnets = {
		Stick = true,
	},

	Stats = {
		Range = 0,
		Agility = 0,
		Capacity = 0,
		Mobility = 0,

		Level = 1,
		Magnetism = "0",
		Rebirth = 0,

		Money = "140",
	},

	Ores = {
		-- ["Copper"] = 0,
		-- ["Iron"] = 0,
		-- ["Silver"] = 0,
		-- ["Gold"] = 0,
		-- ["Platinum"] = 0,
		-- ["Diamond"] = 0,
	},

	Multipliers = {
		Cash = "1",
		Magnetism = "1",
	},
}

return ProfileTemplate
